### ISSUE TITLE
Dont assume hwcrypt is available

### ISSUE THREAD

**Issue by piggz** [sailfishos-open/sailfish-device-encryption-community#18]
The wizard proposes a hwcrypt backed key on the pinephone, which doesnt have it available.  Hwcrypt support should be optional, and turned on/off in device config.

**Comment by rinigus** [comment]
Fixed in https://github.com/sailfishos-open/libsfosdevenc/commit/5ed54d972482e426e6ca692588938cf959c45f5b

No need for config options as we can check if hwcrypt is available
