### ISSUE TITLE
Use systemd-generator for unit creation

### ISSUE THREAD

**Issue by piggz** [sailfishos-open/sailfish-device-encryption-community#19]
Currently, unit files are written by custom program.  Systemd-generators are designed for this, so it might be worth converting the current programs to generators.

**Comment by rinigus** [comment]
For reference: https://www.freedesktop.org/software/systemd/man/systemd.generator.html

**Comment by rinigus** [comment]
Fixed by:

- https://github.com/sailfishos-open/sailfish-device-encryption-community-generator
- https://github.com/sailfishos-open/libsfosdevenc/commit/b7d9f49c335b0a60a77b83cd383d0b866ed57111
